### ISSUE TITLE
Problem with the scritpt discord wi-fi env

### ISSUE THREAD

**Issue by ivoiot** [T-achyon/ducky#1]
with raspeberry pico on windows 10 the script always stucks at the same point as you can see here. have you any suggestion to fix it?

![image](https://github.com/orlandobianco/ducky/assets/116632618/ac62e437-fc66-467d-854c-00855808ffe6)

**Comment by orlandobianco** [comment]
This is strange cause I’ve tested it right now and it works correctly on a flipper zero, have you set the keyboard layout that matches you pc language? (I think Italian)

**Comment by ivoiot** [comment]
I've tested it on a raspberry pi pico and it stucks again at the same part. when the scritp try to imput a bracket it stucks. any suggestion?

**Comment by orlandobianco** [comment]
Please provide more info about the issue, have you tried a different layout? Which script interpreter are you using? As I said I've retested the script and it works, probably there is some issue in your configuration but I can't help without details
